### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'sort' in /examples/image_to_annotations.py

### ISSUE THREAD

**Issue by chenyenru** [facebookresearch/AnimatedDrawings#112]
Hi, when I tried to run my own image by setting up the container and following the tutorial below, it shows an error message.

(animated_drawings) torchserve % cd ../examples
(animated_drawings) examples % python image_to_animation.py drawings/garlic.png garlic_out

Here is the error message:

`Traceback (most recent call last):
  File "/Users/chen_yenru/Documents/GitHub/DATASCIENCE/ML/AnimatedDrawings/examples/image_to_animation.py", line 41, in <module>
    image_to_animation(img_fn, char_anno_dir, motion_cfg_fn, retarget_cfg_fn)
  File "/Users/chen_yenru/Documents/GitHub/DATASCIENCE/ML/AnimatedDrawings/examples/image_to_animation.py", line 19, in image_to_animation
    image_to_annotations(img_fn, char_anno_dir)
  File "/Users/chen_yenru/Documents/GitHub/DATASCIENCE/ML/AnimatedDrawings/examples/image_to_annotations.py", line 59, in image_to_annotations
    detection_results.sort(key=lambda x: x['score'], reverse=True)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'sort'`

I think it's because of Python's version difference, where .sort() is only for Python 2. 

Yet, when I change it to `sort(detection_results, key=lambda x: x['score'], reverse=True)`, it then returns a type error on the indices.

Here is the error message:
`Traceback (most recent call last):
  File "/Users/chen_yenru/Documents/GitHub/DATASCIENCE/ML/AnimatedDrawings/examples/image_to_animation.py", line 41, in <module>
    image_to_animation(img_fn, char_anno_dir, motion_cfg_fn, retarget_cfg_fn)
  File "/Users/chen_yenru/Documents/GitHub/DATASCIENCE/ML/AnimatedDrawings/examples/image_to_animation.py", line 19, in image_to_animation
    image_to_annotations(img_fn, char_anno_dir)
  File "/Users/chen_yenru/Documents/GitHub/DATASCIENCE/ML/AnimatedDrawings/examples/image_to_annotations.py", line 59, in image_to_annotations
    sorted(detection_results, key=lambda x: x['score'], reverse=True)
  File "/Users/chen_yenru/Documents/GitHub/DATASCIENCE/ML/AnimatedDrawings/examples/image_to_annotations.py", line 59, in <lambda>
    sorted(detection_results, key=lambda x: x['score'], reverse=True)
                                            ~^^^^^^^^^
TypeError: string indices must be integers, not 'str'`

I'd like to ask how to overcome this problem?
Thanks!

**Comment by hjessmith** [comment]
Hello,
[.sort() is supported in Python 3](https://docs.python.org/3/library/stdtypes.html#list.sort), so that's not the issue.

The issue is that the response from the torchserver within the docker contain is not in the format expected by the script. Can you inspect or debug the contents of `detection_results` in the line before the error occurs?

**Comment by thhung** [comment]
I have the same issue. The problem is that the prediction was failed on the torchserver side. Here is the content of `detection_results `:
```
{'code': 503, 'type': 'InternalServerException', 'message': 'Prediction failed'}
```

**Comment by hjessmith** [comment]
Were you using the example garlic image or something else? 

This issue from the pytorch github is related to torchserve error debugging https://github.com/pytorch/serve/issues/215

Debugging torchserve is outside my scope of support for now, but if you figure out the cause / resolution please share it.

**Comment by thhung** [comment]
In my case, switching back to CPU solved the issue. It seems there are some problems related to using GPU on the torchserve side.

**Comment by chenyenru** [comment]
Hi thhung, may I ask how you switch back to CPU? Did you mean specifying in Pytorch to use only the CPU?
Regarding that, I'd like to ask whether it's to type `export CUDA_VISIBLE_DEVICES=""` in the shell?

Thanks!

**Comment by thhung** [comment]
@chenyenru I think you can tried `export CUDA_VISIBLE_DEVICES="` to see if it works. I simply turnoff the connection with GPU to force `torchserve` use only CPU. Let me know if you manage to do it. You can try some config on the torchserve side. I did but it doesn't work for me.

**Comment by zsinba** [comment]
the same issue.

**Comment by zsinba** [comment]
Solved it after setting docker 
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/890157/233681746-7241dccd-0036-42f6-bf9f-29817e2b8d45.png">


Hardware: M2 max .
Python:3.11.2
MacOS

**Comment by thhung** [comment]
@zsinba Mine was different with yours. Mine have the 503 error code. I think it is related to GPU implementation. Your case probably is related to the resources.

**Comment by zsinba** [comment]
I don't think it has anything to do with GPU. The M2 Max with  mps,  but not GPU;
And I didn't set the parameters. I guess he still used the cpu

**Comment by zsinba** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/890157/233693052-22e7b443-85f9-4a62-bc96-a82581ec5c22.png">
it's ok
