### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by jinbilly** [facebookresearch/AnimatedDrawings#117]
When I run this command, I get the following error. help ~

I installed the docker environment as instructed, but what's the problem?

➜  examples python3 image_to_animation.py drawings/garlic.png garlic_out

Traceback (most recent call last):
  File "/Users/jinhyeogjun/Desktop/ai/AnimatedDrawings/examples/image_to_animation.py", line 5, in <module>
    from image_to_annotations import image_to_annotations
  File "/Users/jinhyeogjun/Desktop/ai/AnimatedDrawings/examples/image_to_annotations.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by hjessmith** [comment]
Looks like you're missing Python's [requests module](https://pypi.org/project/requests/). 

Make sure you follow the installation instructions, ensure that your virtual environment is activated, and try again.
