### ISSUE TITLE
AttributeError: dlsym(0x2068fe020, CGLGetCurrentContext): symbol not found

### ISSUE THREAD

**Issue by JacquesGodin** [facebookresearch/AnimatedDrawings#126]
> Python 3.10. (already tried with 3.9 and 3.11)
> MacOS Monterey 12.6.5
> PyOpenGL 3.1.5 (already tried with 3.1.6)

Error log
`
>>> from animated_drawings import render
>>> render.start('./examples/config/mvc/interactive_window_example.yaml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/animated_drawings/render.py", line 17, in start
    view = View.create_view(cfg.view)
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/animated_drawings/view/view.py", line 46, in create_view
    from animated_drawings.view.window_view import WindowView
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/animated_drawings/view/window_view.py", line 6, in <module>
    from animated_drawings.view.shaders.shader import Shader
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/animated_drawings/view/shaders/shader.py", line 5, in <module>
    import OpenGL.GL as GL
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/ad/lib/python3.10/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/ad/lib/python3.10/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/ad/lib/python3.10/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/ad/lib/python3.10/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/ad/lib/python3.10/site-packages/OpenGL/error.py", line 183, in __init__
    self._isValid = platform.CurrentContextIsValid
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/ad/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/ad/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 356, in CurrentContextIsValid
    return self.GetCurrentContext
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/ad/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/Users/tg/Projects/ZorbinLabs/app/backend/AnimatedDrawings/ad/lib/python3.10/site-packages/OpenGL/platform/darwin.py", line 62, in GetCurrentContext
    return self.CGL.CGLGetCurrentContext 
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x2068fe020, CGLGetCurrentContext): symbol not found

**Comment by JacquesGodin** [comment]
I did some additional research and the problem was with this variable I previously added to my .zprofile:

`export DYLD_LIBRARY_PATH="/usr/local/lib:$DYLD_LIBRARY_PATH"`

According to this [Stackoverflow,](https://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s) DYLD may cause symbol lookup errors when you override with a library that does not have the same symbol table.

Problem solved!

**Comment by hjessmith** [comment]
Thanks for solving that, @JacquesGodin ... frankly I had no idea how to respond to your issue.

Closing out the issue.
