### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'sort'

### ISSUE THREAD

**Issue by dhs964057117** [facebookresearch/AnimatedDrawings#137]
os:Ubuntu 20.04.3 LTS
i tried to resolved my own picture
when i run the cmd `python image_to_animation.py drawings/garlic.png garlic_out`
i got the error 
`Traceback (most recent call last):
  File "image_to_animation.py", line 41, in <module>
    image_to_animation(img_fn, char_anno_dir, motion_cfg_fn, retarget_cfg_fn)
  File "image_to_animation.py", line 19, in image_to_animation
    image_to_annotations(img_fn, char_anno_dir)
  File "/home/dhs/下载/AnimatedDrawings/examples/image_to_annotations.py", line 60, in image_to_annotations
    detection_results.sort(key=lambda x: x['score'], reverse=True)
AttributeError: 'dict' object has no attribute 'sort'
`
i tried to add log and debug the project i got this
`DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8080
DEBUG:urllib3.connectionpool:http://localhost:8080 "POST /predictions/drawn_humanoid_detector HTTP/1.1" 507 84
INFO:root:{'code': 507, 'type': 'InternalServerException', 'message': 'Worker died.'}
`

**Comment by dhs964057117** [comment]
> os:Ubuntu 20.04.3 LTS 我试图 在运行 cmd 时解决我自己的图片`python image_to_animation.py drawings/garlic.png garlic_out` 我得到了错误 `Traceback (most recent call last): File "image_to_animation.py", line 41, in <module> image_to_animation(img_fn, char_anno_dir, motion_cfg_fn, retarget_cfg_fn) File "image_to_animation.py", line 19, in image_to_animation image_to_annotations(img_fn, char_anno_dir) File "/home/dhs/下载/AnimatedDrawings/examples/image_to_annotations.py", line 60, in image_to_annotations detection_results.sort(key=lambda x: x['score'], reverse=True) AttributeError: 'dict' object has no attribute 'sort' ` 我试图添加日志并调试项目我得到了这个 `DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8080 DEBUG:urllib3.connectionpool:http://localhost:8080 "POST /predictions/drawn_humanoid_detector HTTP/1.1" 507 84 INFO:root:{'code': 507, 'type': 'InternalServerException', 'message': 'Worker died.'} `

i have resolve this problem by configure docker settings that select settings,advanced and increase the cpu，memory and swap
![image](https://user-images.githubusercontent.com/34617909/233896542-04b44fad-75e5-4c39-a35c-4211144635f3.png)
