### ISSUE TITLE
cannot  generate a video headlessly 

### ISSUE THREAD

**Issue by koaqiu** [facebookresearch/AnimatedDrawings#167]
Ubuntu 18.04. 

```
>>> from animated_drawings import render
>>> render.start('./examples/config/mvc/export_gif_example.yaml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/AnimatedDrawings/animated_drawings/render.py", line 17, in start
    view = View.create_view(cfg.view)
  File "/root/AnimatedDrawings/animated_drawings/view/view.py", line 43, in create_view
    from animated_drawings.view.mesa_view import MesaView
  File "/root/AnimatedDrawings/animated_drawings/view/mesa_view.py", line 8, in <module>
    from OpenGL import GL, osmesa
  File "/opt/conda/lib/python3.10/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/opt/conda/lib/python3.10/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/opt/conda/lib/python3.10/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/opt/conda/lib/python3.10/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
```

**Comment by koaqiu** [comment]
Python 3.8.13

```
Python 3.8.13 (default, Oct 21 2022, 23:50:54)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from animated_drawings import render
>>> render.start('./examples/config/mvc/export_gif_example.yaml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/AnimatedDrawings/animated_drawings/render.py", line 17, in start
    view = View.create_view(cfg.view)
  File "/root/AnimatedDrawings/animated_drawings/view/view.py", line 43, in create_view
    from animated_drawings.view.mesa_view import MesaView
  File "/root/AnimatedDrawings/animated_drawings/view/mesa_view.py", line 8, in <module>
    from OpenGL import GL, osmesa
  File "/opt/conda/envs/animated_drawings/lib/python3.8/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/opt/conda/envs/animated_drawings/lib/python3.8/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/opt/conda/envs/animated_drawings/lib/python3.8/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/opt/conda/envs/animated_drawings/lib/python3.8/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'
```

**Comment by koaqiu** [comment]
#99 this work to me
