### ISSUE TITLE
how to use on linux centos errro:shader.py", line 41, in __init__    assert False, msg AssertionError: Error compiling shaders

### ISSUE THREAD

**Issue by forever1dream** [facebookresearch/AnimatedDrawings#209]
when I use on centos , error:
(animated) [xxx@localhost examples]$ python image_to_animation.py ./drawings/garlic.png garlic_out
/home/anaconda3/envs/animated/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
/home/anaconda3/envs/animated/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "image_to_animation.py", line 41, in <module>
    image_to_animation(img_fn, char_anno_dir, motion_cfg_fn, retarget_cfg_fn)
  File "image_to_animation.py", line 22, in image_to_animation
    annotations_to_animation(char_anno_dir, motion_cfg_fn, retarget_cfg_fn)
  File "/home/work/python/AnimatedDrawings/examples/annotations_to_animation.py", line 40, in annotations_to_animation
    animated_drawings.render.start(output_mvc_cfn_fn)
  File "/home/work/python/AnimatedDrawings/animated_drawings/render.py", line 17, in start
    view = View.create_view(cfg.view)
  File "/home/work/python/AnimatedDrawings/animated_drawings/view/view.py", line 47, in create_view
    return WindowView(view_cfg)
  File "/home/work/python/AnimatedDrawings/animated_drawings/view/window_view.py", line 38, in __init__
    self._prep_shaders()
  File "/home/work/python/AnimatedDrawings/animated_drawings/view/window_view.py", line 72, in _prep_shaders
    self._initiatize_shader('bvh_shader', str(BVH_VERT), str(BVH_FRAG))
  File "/home/work/python/AnimatedDrawings/animated_drawings/view/window_view.py", line 102, in _initiatize_shader
    self.shaders[shader_name] = Shader(vert_path, frag_path)
  File "/home/work/python/AnimatedDrawings/animated_drawings/view/shaders/shader.py", line 41, in __init__
    assert False, msg
AssertionError: Error compiling shaders

How can I del the viewer

**Comment by httzipdev** [comment]
If you set up `USE_MESA: True` in `mvc_base_cfg.yaml` but still not working. Try putting it in `annotations_to_animation.py` in line 27
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/14134588/06715585-0956-46ac-bea1-799d40ba4a0c)

You may need to install osmesa inside the `conda` https://github.com/facebookresearch/AnimatedDrawings/issues/158#issuecomment-1545289898

**Comment by hjessmith** [comment]
Sorry, there's no way to delete the viewer and have it work. Try httzipdev's suggestions. You can reopen if it's still an active problem for you.
