### ISSUE TITLE
Problem with installation on Windows

### ISSUE THREAD

**Issue by tigran-sargsyan-w** [facebookresearch/AnimatedDrawings#239]
- [x]   # create and activate the virtual environment
- [x]     conda create --name animated_drawings python=3.8.13
- [x]     conda activate animated_drawings
- [x]     # clone AnimatedDrawings and use pip to install
- [x]     git clone https://github.com/facebookresearch/AnimatedDrawings.git
- [x]     cd AnimatedDrawings
- [ ]     pip install -e .

**I followed all the instructions but I get an error when installing  - pip install -e .** _Please help me resolve this issue_

(animated_drawings) PS C:\Users\tigra\AnimatedDrawings\AnimatedDrawings> pip install -e .
Obtaining file:///C:/Users/tigra/AnimatedDrawings/AnimatedDrawings
  Preparing metadata (setup.py) ... done
Collecting numpy==1.23.3 (from animated-drawings==0.0.0)
  Downloading numpy-1.23.3-cp311-cp311-win_amd64.whl (14.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 54.4 MB/s eta 0:00:00
Collecting scipy==1.10.0 (from animated-drawings==0.0.0)
  Downloading scipy-1.10.0-cp311-cp311-win_amd64.whl (42.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 MB 50.4 MB/s eta 0:00:00
Collecting scikit-image==0.19.3 (from animated-drawings==0.0.0)
  Downloading scikit-image-0.19.3.tar.gz (22.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.2/22.2 MB 81.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scikit-learn==1.1.2 (from animated-drawings==0.0.0)
  Downloading scikit-learn-1.1.2.tar.gz (7.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 37.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      Partial import of sklearn during the build process.
      setup.py:128: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html

        from numpy.distutils.command.build_ext import build_ext  # noqa
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      Traceback (most recent call last):
        File "C:\Users\tigra\.conda\envs\animated_drawings\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\tigra\.conda\envs\animated_drawings\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tigra\.conda\envs\animated_drawings\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tigra\AppData\Local\Temp\pip-build-env-2se_6gku\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\tigra\AppData\Local\Temp\pip-build-env-2se_6gku\overlay\Lib\site-packages\setuptools\build_meta.py", line 268, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tigra\AppData\Local\Temp\pip-build-env-2se_6gku\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 329, in <module>
          setup_package()
        File "setup.py", line 325, in setup_package
          setup(**metadata)
        File "C:\Users\tigra\AppData\Local\Temp\pip-build-env-2se_6gku\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
          config = configuration()
                   ^^^^^^^^^^^^^^^
        File "setup.py", line 187, in configuration
          config.add_subpackage("sklearn")
        File "C:\Users\tigra\AppData\Local\Temp\pip-build-env-2se_6gku\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1050, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tigra\AppData\Local\Temp\pip-build-env-2se_6gku\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1016, in get_subpackage
          config = self._get_configuration_from_setup_py(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tigra\AppData\Local\Temp\pip-build-env-2se_6gku\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 958, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tigra\AppData\Local\Temp\pip-install-3curf0xc\scikit-learn_71cd584f67c149838f03cb71e7025e41\sklearn\setup.py", line 85, in configuration
          cythonize_extensions(top_path, config)
        File "C:\Users\tigra\AppData\Local\Temp\pip-install-3curf0xc\scikit-learn_71cd584f67c149838f03cb71e7025e41\sklearn\_build_utils\__init__.py", line 47, in cythonize_extensions
          basic_check_build()
        File "C:\Users\tigra\AppData\Local\Temp\pip-install-3curf0xc\scikit-learn_71cd584f67c149838f03cb71e7025e41\sklearn\_build_utils\pre_build_helpers.py", line 119, in basic_check_build
          compile_test_program(code)
        File "C:\Users\tigra\AppData\Local\Temp\pip-install-3curf0xc\scikit-learn_71cd584f67c149838f03cb71e7025e41\sklearn\_build_utils\pre_build_helpers.py", line 75, in compile_test_program
          ccompiler.compile(
        File "C:\Users\tigra\AppData\Local\Temp\pip-build-env-2se_6gku\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
          self.initialize()
        File "C:\Users\tigra\AppData\Local\Temp\pip-build-env-2se_6gku\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tigra\AppData\Local\Temp\pip-build-env-2se_6gku\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tigra\AppData\Local\Temp\pip-build-env-2se_6gku\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by hjessmith** [comment]
Hi @tigran-sargsyan-w 

Your issue looks specific to sklearn and not Animated Drawings. I would recommend you try creating a clean conda environment with python 3.8.13 and try using pip to install sklearn version 1.1.2. If that doesn't work, I would contact the sklearn community to figure out why. 

I'm closing out the issue, but please feel free to update it with your resolution.
