### ISSUE TITLE
Installation error on Mac M2

### ISSUE THREAD

**Issue by Conghdos** [facebookresearch/AnimatedDrawings#244]
**When installing on MacBook M2 I get the following error**

(animated_drawings) hoangduccong@192 Python % git clone https://github.com/facebookresearch/AnimatedDrawings.git
    cd AnimatedDrawings
    pip install -e .
Cloning into 'AnimatedDrawings'...
remote: Enumerating objects: 856, done.
remote: Counting objects: 100% (416/416), done.
remote: Compressing objects: 100% (234/234), done.
remote: Total 856 (delta 210), reused 335 (delta 172), pack-reused 440
Receiving objects: 100% (856/856), 110.38 MiB | 2.73 MiB/s, done.
Resolving deltas: 100% (363/363), done.
Obtaining file:///Users/hoangduccong/code/GoldenMind/Python/AnimatedDrawings
  Preparing metadata (setup.py) ... done
Collecting numpy==1.23.3 (from animated-drawings==0.0.0)
  Using cached numpy-1.23.3-cp38-cp38-macosx_11_0_arm64.whl (13.3 MB)
Collecting scipy==1.10.0 (from animated-drawings==0.0.0)
  Using cached scipy-1.10.0-cp38-cp38-macosx_12_0_arm64.whl (28.8 MB)
Collecting scikit-image==0.19.3 (from animated-drawings==0.0.0)
  Using cached scikit_image-0.19.3-cp38-cp38-macosx_12_0_arm64.whl (12.4 MB)
Collecting scikit-learn==1.1.2 (from animated-drawings==0.0.0)
  Using cached scikit_learn-1.1.2-cp38-cp38-macosx_12_0_arm64.whl (7.6 MB)
Collecting shapely==1.8.5.post1 (from animated-drawings==0.0.0)
  Using cached Shapely-1.8.5.post1-cp38-cp38-macosx_11_0_arm64.whl (1.1 MB)
Collecting opencv-python==4.6.0.66 (from animated-drawings==0.0.0)
  Using cached opencv_python-4.6.0.66-cp37-abi3-macosx_11_0_arm64.whl (30.0 MB)
Collecting Pillow==9.3.0 (from animated-drawings==0.0.0)
  Using cached Pillow-9.3.0-cp38-cp38-macosx_11_0_arm64.whl (2.9 MB)
Collecting glfw==2.5.5 (from animated-drawings==0.0.0)
  Using cached glfw-2.5.5-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-macosx_11_0_arm64.whl (91 kB)
Collecting PyOpenGL==3.1.6 (from animated-drawings==0.0.0)
  Using cached PyOpenGL-3.1.6-py3-none-any.whl (2.4 MB)
Collecting PyYAML==6.0 (from animated-drawings==0.0.0)
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/hoangduccong/miniconda3/envs/animated_drawings/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/hoangduccong/miniconda3/envs/animated_drawings/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/hoangduccong/miniconda3/envs/animated_drawings/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 318, in run
          self.find_sources()
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
          mm.run()
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 548, in run
          self.add_defaults()
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/hj/t56wcwfd1gs8hwpt60lhy3rh0000gn/T/pip-build-env-lj9eqzwp/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ujey02** [comment]
I worked it out by commenting out that package and install it separately

**Comment by yihleego** [comment]
Please try to edit setup.py `PyYAML==6.0` -> `PyYAML==6.0.1`

https://github.com/facebookresearch/AnimatedDrawings/blob/3de5521c0bb7464180590b8c8988a51c1227b967/setup.py#L1-L30

**Comment by Conghdos** [comment]
Thank you, I have fixed it according to your instructions
