### ISSUE TITLE
call the server in docker,raise error.Then the server turn to unhealthy,the memory is 16GB

### ISSUE THREAD

**Issue by SEVENBAY** [facebookresearch/AnimatedDrawings#271]
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/39325219/decc159e-024e-405c-9ce9-4a62342b6246)

2024-03-04 17:56:14 java.lang.InterruptedException: null
2024-03-04 17:56:14     at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1081) ~[?:?]
2024-03-04 17:56:14     at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369) ~[?:?]
2024-03-04 17:56:14     at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278) ~[?:?]
2024-03-04 17:56:14     at org.pytorch.serve.wlm.WorkerThread.connect(WorkerThread.java:424) ~[model-server.jar:?]
2024-03-04 17:56:14     at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:191) [model-server.jar:?]
2024-03-04 17:56:14     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2024-03-04 17:56:14     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2024-03-04 17:56:14     at java.lang.Thread.run(Thread.java:829) [?:?]
2024-03-04 17:56:14 2024-03-04T09:56:14,254 [DEBUG] W-9003-drawn_humanoid_detector_1.0 org.pytorch.serve.wlm.WorkerThread - W-9003-drawn_humanoid_detector_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2024-03-04 17:56:14 2024-03-04T09:56:14,255 [WARN ] W-9003-drawn_humanoid_detector_1.0 org.pytorch.serve.wlm.WorkerThread - Auto recovery failed again
2024-03-04 17:56:14 2024-03-04T09:56:14,256 [WARN ] W-9003-drawn_humanoid_detector_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9003-drawn_humanoid_detector_1.0-stderr
2024-03-04 17:56:14 2024-03-04T09:56:14,256 [WARN ] W-9003-drawn_humanoid_detector_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9003-drawn_humanoid_detector_1.0-stdout
2024-03-04 17:56:14 2024-03-04T09:56:14,266 [INFO ] W-9003-drawn_humanoid_detector_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9003-drawn_humanoid_detector_1.0-stdout
2024-03-04 17:56:14 2024-03-04T09:56:14,266 [INFO ] W-9003-drawn_humanoid_detector_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9003-drawn_humanoid_detector_1.0-stderr
2024-03-04 17:56:14 2024-03-04T09:56:14,267 [ERROR] epollEventLoopGroup-5-4 org.pytorch.serve.wlm.WorkerThread - Unknown exception
2024-03-04 17:56:14 io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/39325219/850305e4-bb04-44ad-9a24-90673e6697a8)

**Comment by SunshineList** [comment]
I have also encountered the same problem. Have you solved it？

**Comment by SunshineList** [comment]
I just solved this problem. Please check if there are any Python errors on the project when it starts running, and then try to solve this error. In the end, I lowered the version of Torch. Pay attention to Torchvision. I first lowered Torch=2.0.1, and then the Torchvision and Torch versions were incorrect. I also lowered Torchvision to 0.15.1, which will automatically install Torch=2.0.0. This will solve my problem

**Comment by SEVENBAY** [comment]
> I just solved this problem. Please check if there are any Python errors on the project when it starts running, and then try to solve this error. In the end, I lowered the version of Torch. Pay attention to Torchvision. I first lowered Torch=2.0.1, and then the Torchvision and Torch versions were incorrect. I also lowered Torchvision to 0.15.1, which will automatically install Torch=2.0.0. This will solve my problem

I deployed based on Docker Desktop in Windows 11. Will there be any environmental issues? What platform are you running the project on？

**Comment by SunshineList** [comment]
> > I just solved this problem. Please check if there are any Python errors on the project when it starts running, and then try to solve this error. In the end, I lowered the version of Torch. Pay attention to Torchvision. I first lowered Torch=2.0.1, and then the Torchvision and Torch versions were incorrect. I also lowered Torchvision to 0.15.1, which will automatically install Torch=2.0.0. This will solve my problem
> 
> I deployed based on Docker Desktop in Windows 11. Will there be any environmental issues? What platform are you running the project on？

I am also docker desktop

**Comment by SEVENBAY** [comment]
> > > I just solved this problem. Please check if there are any Python errors on the project when it starts running, and then try to solve this error. In the end, I lowered the version of Torch. Pay attention to Torchvision. I first lowered Torch=2.0.1, and then the Torchvision and Torch versions were incorrect. I also lowered Torchvision to 0.15.1, which will automatically install Torch=2.0.0. This will solve my problem
> > 
> > 
> > I deployed based on Docker Desktop in Windows 11. Will there be any environmental issues? What platform are you running the project on？
> 
> You can try my method. I have solved it now and can be used normally，If there are still any questions, you can send them out and take a look together

when run the scripts, get error like this, do you kown why?
(animate_draw) E:\pyproject\xianyuproject\AnimatedDrawings\examples>python image_to_animation.py drawings/garlic.png garlic_out
Traceback (most recent call last):
  File "E:\pyproject\xianyuproject\AnimatedDrawings\examples\image_to_animation.py", line 6, in <module>
    from annotations_to_animation import annotations_to_animation
  File "E:\pyproject\xianyuproject\AnimatedDrawings\examples\annotations_to_animation.py", line 4, in <module>
    import animated_drawings.render
ModuleNotFoundError: No module named 'animated_drawings'

**Comment by SunshineList** [comment]
> > > > I just solved this problem. Please check if there are any Python errors on the project when it starts running, and then try to solve this error. In the end, I lowered the version of Torch. Pay attention to Torchvision. I first lowered Torch=2.0.1, and then the Torchvision and Torch versions were incorrect. I also lowered Torchvision to 0.15.1, which will automatically install Torch=2.0.0. This will solve my problem
> > > 
> > > 
> > > I deployed based on Docker Desktop in Windows 11. Will there be any environmental issues? What platform are you running the project on？
> > 
> > 
> > You can try my method. I have solved it now and can be used normally，If there are still any questions, you can send them out and take a look together
> 
> when run the scripts, get error like this, do you kown why? (animate_draw) E:\pyproject\xianyuproject\AnimatedDrawings\examples>python image_to_animation.py drawings/garlic.png garlic_out Traceback (most recent call last): File "E:\pyproject\xianyuproject\AnimatedDrawings\examples\image_to_animation.py", line 6, in from annotations_to_animation import annotations_to_animation File "E:\pyproject\xianyuproject\AnimatedDrawings\examples\annotations_to_animation.py", line 4, in import animated_drawings.render ModuleNotFoundError: No module named 'animated_drawings'

Look at the import animated_drawings.reader of examples\annotations_to_animation file Is there an error reported?

**Comment by SEVENBAY** [comment]
> I just solved this problem. Please check if there are any Python errors on the project when it starts running, and then try to solve this error. In the end, I lowered the version of Torch. Pay attention to Torchvision. I first lowered Torch=2.0.1, and then the Torchvision and Torch versions were incorrect. I also lowered Torchvision to 0.15.1, which will automatically install Torch=2.0.0. This will solve my problem

After adjusting according to your instructions, I successfully ran it. Thank you!
