### ISSUE TITLE
'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by MohamedHussein736** [facebookresearch/AnimatedDrawings#89]
Hi,

When I am running "render.start('./examples/config/mvc/interactive_window_example.yaml')"
I have this error 'NoneType' object has no attribute 'decode'

**Comment by hjessmith** [comment]
I think an issue with OpenGL can cause that message. 

Please copy and paste the terminal output that you get when that error is thrown.

Additionally, tell me what OS you're using and whether it's a local computer or something you're accessing remotely (e.g. a cloud server you're SSHing into)

**Comment by MohamedHussein736** [comment]
OS: Ubuntu, using my local machine
This is the error
```
python 3.8.13 (default, Oct 21 2022, 23:50:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from animated_drawings import render
>>> render.start('./examples/config/mvc/interactive_window_example.yaml')
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
/home/mohamed/anaconda3/envs/animated_drawings/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65543) b'GLX: Failed to create context: GLXBadFBConfig'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mohamed/Desktop/AnimatedDrawings/AnimatedDrawings/animated_drawings/render.py", line 15, in start
    view = View.create_view(cfg.view)
  File "/home/mohamed/Desktop/AnimatedDrawings/AnimatedDrawings/animated_drawings/view/view.py", line 45, in create_view
    return WindowView(view_cfg)
  File "/home/mohamed/Desktop/AnimatedDrawings/AnimatedDrawings/animated_drawings/view/window_view.py", line 32, in __init__
    self._create_window(*cfg.window_dimensions)  # pyright: ignore[reportGeneralTypeIssues]
  File "/home/mohamed/Desktop/AnimatedDrawings/AnimatedDrawings/animated_drawings/view/window_view.py", line 124, in _create_window
    logging.info(f'OpenGL Version: {GL.glGetString(GL.GL_VERSION).decode()}')  # pyright: ignore[reportGeneralTypeIssues]
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by hjessmith** [comment]
And what is the version number of your Ubuntu?

**Comment by MohamedHussein736** [comment]
Ubuntu 22.04.2 LTS

**Comment by hjessmith** [comment]
Okay. The project has been tested with Mac OS and Ubuntu 18.04, but not 22.04. Your issue is a good indicator that I need to list that explicitly within the Readme.

I haven't encountered your issue before, but it looks related to the version of libGL on your machine. This SO flags the same issue and has some proposed resolutions:
https://stackoverflow.com/questions/72110384/libgl-error-mesa-loader-failed-to-open-iris

Please take a look and, if they successfully resolve your issue, I'd appreciate you updating this issue letting us know.

**Comment by MohamedHussein736** [comment]
I tried your link and still not working, I will try it on ubuntu  18.04.

**Comment by oarcher** [comment]
for me, with ubuntu 23.04, `conda install -c conda-forge libstdcxx-ng` solve the pb.
